<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Daftar sekarang</name>
   <tag></tag>
   <elementGuidId>9a494351-5cd0-4747-be39-f589a1f91772</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div/div[2]/div/div[1]/div[6]/center/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal.fade.lupa-example-modal-lg.show > div.modal-dialog.modal-lg > div.modal-content > div.modal-body > div.row > div.col-md-6 > div.info--register-bottom > center > a.btn-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f06d7b5-41cd-4941-a984-9f4cfeda9533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/auth/login</value>
      <webElementGuid>e8f70fa7-0498-42be-8c01-f1be0f241e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-register</value>
      <webElementGuid>182a2f0a-7089-4154-89a4-824cc2c82566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>2bef84a4-5194-4a33-abd5-38ba453247f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Daftar sekarang!</value>
      <webElementGuid>2d5144de-533c-4736-8e26-5422df10f823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;modal fade lupa-example-modal-lg show&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;info--register-bottom&quot;]/center[1]/a[@class=&quot;btn-register&quot;]</value>
      <webElementGuid>aff6eb7b-426c-456a-9c25-4b787e15772f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Daftar sekarang!')])[2]</value>
      <webElementGuid>328d5f03-871c-4e9b-93e7-47a955073367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum punya akun?'])[2]/following::a[1]</value>
      <webElementGuid>22a2a0e2-fbec-4535-a781-9b55cacfc265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Hadiah'])[2]/following::a[1]</value>
      <webElementGuid>07130b79-9b24-4383-953c-4e6fa1c67391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LUPA PASSWORD?'])[1]/preceding::a[1]</value>
      <webElementGuid>67148c33-1877-4ba6-92f6-9ce0a25c1858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username, Email'])[1]/preceding::a[1]</value>
      <webElementGuid>4689693b-589e-486e-adfb-58173d1dfa7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://10.9.2.63/ecommerce/auth/login')])[2]</value>
      <webElementGuid>f8f226bf-ba48-44bb-bcd5-3473a241f58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div[6]/center/a</value>
      <webElementGuid>63ec32a5-7362-418e-876b-2078553d4452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/auth/login' and (text() = 'Daftar sekarang!' or . = 'Daftar sekarang!')]</value>
      <webElementGuid>85784a43-596c-4231-ac58-23e9ff890063</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
