<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_masukHalamanReg</name>
   <tag></tag>
   <elementGuidId>3f78e00c-4082-434a-9706-aab02194a491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Masuk')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.ps-tab-list > li > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ded3563-7f9a-4080-8cb7-ab8e5d9ac285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#sign-in</value>
      <webElementGuid>f2db5b87-b1e4-41e7-98d0-a57536f31a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>60eb495d-8b59-41ea-b031-12fd0749d4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-my-account&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-form--account ps-tab-root&quot;]/ul[@class=&quot;ps-tab-list&quot;]/li[1]/a[1]</value>
      <webElementGuid>9659c407-ec55-4091-8936-471ccda250ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masuk')]</value>
      <webElementGuid>e6c1926c-8673-4755-8e33-24d8e6e9f80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='White'])[1]/following::a[1]</value>
      <webElementGuid>1e3910d8-5465-4e99-b56a-65602aade77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yellow'])[1]/following::a[2]</value>
      <webElementGuid>d879552a-6de3-4128-99fc-45fd3b515fa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/preceding::a[1]</value>
      <webElementGuid>a5f3bdeb-b266-440b-8133-45bf5b3e0442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silahkan Masuk ke Akunnya.'])[1]/preceding::a[2]</value>
      <webElementGuid>a8cde8c0-6b5e-43d3-815f-7c0d2043bb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#sign-in')]</value>
      <webElementGuid>275d11af-c28a-4f71-aecf-a86e33265922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/ul/li/a</value>
      <webElementGuid>7cd87f73-bf12-42c3-bf82-59ace5c78681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#sign-in' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>db455813-954f-4692-95e6-4fac5a3cff0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
