<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_emailUsernameLupaPass</name>
   <tag></tag>
   <elementGuidId>9f32ac42-632d-45c5-a5d7-296627050171</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.modal.fade.lupa-example-modal-lg.show > div.modal-dialog.modal-lg > div.modal-content > div.modal-body > div.row > div.col-md-6 > form > div.ps-form__content > div.form-group > input[name=&quot;a&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='a'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9264d3c2-dbb2-4382-8094-03ebcc320d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>122d86cf-f414-4671-9e8d-a10c37d17d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>33a1fbc5-90c5-4a10-9960-b3c2ccc259a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4885998-8a2d-4142-b0a6-4e497428c15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;modal fade lupa-example-modal-lg show&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/form[1]/div[@class=&quot;ps-form__content&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f49fd212-8aa1-4533-9cd6-d9576c8a491a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='a'])[2]</value>
      <webElementGuid>159ad07f-34c1-45b1-aec0-b29797605945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[2]/form/div/div/input</value>
      <webElementGuid>3f6435d0-df23-4e71-87ee-fd1d2151c7a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'a' and @type = 'text']</value>
      <webElementGuid>83309262-4d43-4a4b-854d-0a6b4f6246c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
