<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pengaturan</name>
   <tag></tag>
   <elementGuidId>65e90e59-4da3-42dc-990a-d95e84c439d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.ps-dropdown-menu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Pengaturan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8ee58c69-d208-4599-979c-8fd9368f0441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/members/profil_toko</value>
      <webElementGuid>bb6f5063-aa64-4daa-bc45-41a5c6680c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Pengaturan</value>
      <webElementGuid>c49adebf-2ae9-483f-af94-443c8482f98d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/header[@class=&quot;header header--1&quot;]/div[@class=&quot;header__topone&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;header__right&quot;]/ul[@class=&quot;header__top-links&quot;]/li[2]/div[@class=&quot;ps-dropdown&quot;]/ul[@class=&quot;ps-dropdown-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>eb4c4644-0377-40b7-8dd1-6a7c9c284c42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pengaturan')]</value>
      <webElementGuid>47c72fd0-7a24-4ee3-90d1-42dcb72f3cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telusuri Pesanan'])[1]/following::a[2]</value>
      <webElementGuid>3adb3d41-da9e-40aa-9fe8-fe59d7820c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengiriman gratis'])[3]/following::a[3]</value>
      <webElementGuid>d23a4ad1-d8e6-4d99-9d3c-c9389ca69964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Produk'])[1]/preceding::a[1]</value>
      <webElementGuid>296e16d5-555b-480f-a5d9-2784278a93a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pengaturan']/parent::*</value>
      <webElementGuid>a30ad35d-db9f-4d38-becb-b71389e02b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/members/profil_toko')]</value>
      <webElementGuid>2d614f76-7d1d-4e44-bf5c-78e537530c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/ul/li/a</value>
      <webElementGuid>fb565cdd-67c2-4328-93b8-16ab56208b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/members/profil_toko' and (text() = ' Pengaturan' or . = ' Pengaturan')]</value>
      <webElementGuid>e7ffa2e0-e1c1-45f3-8cbe-fc7771816f9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
