<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-Kecamatan-</name>
   <tag></tag>
   <elementGuidId>08670de5-6bb7-4af1-97ed-917fbaa785b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[10]/div/div/div/div[2]/figure/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list_kecamatan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f66a156e-de0d-45c6-b464-b27a2ab414a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>ebd576b4-6e96-41fe-8aed-10cd18eda69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kecamatan_id</value>
      <webElementGuid>8c461743-e775-492a-a0ee-170f4e2b8def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_kecamatan</value>
      <webElementGuid>74b3e75a-d07b-4c2c-87bd-351f7f6cdebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kecamatan</value>
      <webElementGuid>084cbd0c-5892-466f-b59c-8c1c8c0b1ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_kecamatan&quot;)</value>
      <webElementGuid>9126061e-0e28-493f-bb47-7d7d3d361d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_kecamatan']</value>
      <webElementGuid>09b0aa2c-3940-4dcd-b4f4-5065ca653612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daerah Pengiriman'])[1]/following::select[3]</value>
      <webElementGuid>520e1b0f-3725-420a-afc6-c04ce1468954</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Toko'])[1]/following::select[3]</value>
      <webElementGuid>e708adb4-76dc-40fd-83ac-fb36d86a8c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Lengkap'])[1]/preceding::select[1]</value>
      <webElementGuid>3f76dfa5-562d-4a3b-ac78-cbef2adcde3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontak Toko'])[1]/preceding::select[1]</value>
      <webElementGuid>199ecf2c-5c92-4b8b-9312-3f6c8fc26ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>d97271e8-c63a-4590-a207-488a29d2c704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kecamatan_id' and @id = 'list_kecamatan' and (text() = 'Kecamatan' or . = 'Kecamatan')]</value>
      <webElementGuid>a39dcdbf-aa8a-48af-bf30-75fe9b9ce38c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
