<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-DFTR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>38522f49-9b0b-4dea-a8cc-ed91c6413e86</testSuiteGuid>
   <testCaseLink>
      <guid>3d0a4ee6-f53e-450d-9ccf-a1776bb1cb88</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec47646e-edbf-4474-823e-c2231ef8b71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38bdb975-1951-4ec6-b6b7-72ab64eda37a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0725c607-5084-44ed-9a22-249243ecef1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c822c1f8-7691-486c-a249-ce4a29443334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff8dbb-9ead-425e-8ff5-6518783c4bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837b926a-4819-427f-bac7-5638fef6ab44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>91330640-e712-4b65-9f14-5cd078fd76b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9feaba6d-0f0b-482b-998c-3308b72fafdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9430122-c8d4-4f5f-af59-4171bcd680dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b28a3dfc-adc4-41f0-92da-cd622d4ec656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f8ea3be-3f14-4b69-b54d-83d792205d48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f511144-ed87-454f-bc7f-3332efacab38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>297b42b8-0a27-4b5d-9474-9cc21da53a75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>83f02598-38d0-47b8-8c76-4dcaf7d141a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a27bf70b-ec8d-4f18-9fdb-b09bd02c0e6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f301dff-542a-47b3-89e0-0272e296af06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b43a2a78-8d03-4968-9b6a-aa2915b97a60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20644f0f-443a-4072-bbc3-591f3ea8be9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>567db3cc-6f7e-4db1-a485-e74bcace8af3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0154a6da-285c-4dce-9406-cb45c591c55a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e861dd27-2e64-48a0-856b-2bb7f884903a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d4ede47f-5583-4c86-959c-40bf31379edb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb1e5709-85a2-4561-be4c-65078e68ac93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>875b93e7-8ff6-4824-bfa3-d36f83ed25f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d4468d-f186-4f38-9dcb-28954af7bf89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1efa0bc6-f1c5-445e-acf1-06786fbc9b0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbc7bb2d-633a-4c87-a2a0-a9d0084ef7af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10c8d0dc-70f2-4a9f-b38c-12843b09376b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af09c6ea-55ce-43b7-8e61-25b8ecff190e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>158f62d6-4f68-412d-a7c7-37f5c59d9aed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87415197-721b-4e31-937d-285f642418a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f066e1a-082f-4630-9bc6-6b87444ff28c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea4b270-0717-4b93-9372-7c6633ee6596</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>611f0723-337e-43f1-a90f-5a3d13f76038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd0218a-3391-403f-a104-647e7d741d5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dc900e43-d9b3-4b3e-8aac-c59c9cb1513c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48913f99-19ac-44b9-806c-dda871de4732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa522ba4-306a-4951-9c97-3b75e6497ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d9b1e8-d32e-47f9-9591-f44c4f348d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>769bcc24-e938-47ce-b330-c8e73a49caae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a07483-b00a-4749-ae07-20db07c850e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>308d460e-5eac-406f-95fe-80474a0186f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b27bebc-2623-461a-9345-8db50a259cb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abc72f22-ad44-4e1e-864b-1d812e0bf4c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6781cd-5353-4efc-8d74-7467271cf85a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e0d3601-d6d6-4967-8c50-68a1e5b0bb32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361749d0-9ad0-40af-9480-1cd00d880e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a253f67-ad23-468a-966c-e7dcf8de56ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269004cd-9d06-4d15-962a-f99b481aeed4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8882717f-f014-45e2-9daa-f8da961783c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81d97f0c-3562-4fca-bee2-e36472901f67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09aa359b-1453-47ff-9124-0c3faab83738</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56066f08-1d58-44a6-be84-6d0035b3f276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7158473-d2bb-4e97-9c2e-20c1af756dab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b81fb07d-52e0-449a-b42f-6584ac6314e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aa703c1-a467-4675-b8e0-f87ebe69f8c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d57aa71-6715-42ae-8f00-0e5bf52311be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f6b1a17-0b30-44f1-9ec9-b021bf9f03fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f17ada-6815-4960-8515-c253cda45f7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eeec88e-76c6-425f-832c-4d553652a87d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b4ba69f-983e-4b9b-ae8a-c3da55c0ad56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5196bf7c-a834-4e13-b0b0-5c41599aaa75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>845cfb1a-9fa4-4a18-8a16-aaadefe66257</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1020cc27-18c9-4b2b-93b9-338f7abc8f8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf6192ac-d66b-469f-b7fd-3f1943339414</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae9f958c-8419-432d-995c-3490cc4367ed</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea7a70bf-c7fb-4391-b567-cc9c83ff72da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de18cab2-c6b2-446a-8009-dc59f85b0203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39299d03-c9d6-42da-afa4-6768e6894a54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82c0d3e6-05de-4f8b-842f-6d19fa0168a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bab105-8998-4ba8-a025-edcc446ca98f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d42c980-e053-40da-9401-2971bc8ab6bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b30799fc-d915-43b7-ad6e-fc52965f3c59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa1c5cd6-7089-4863-bd92-ce8912a42704</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>198bdf3c-5838-4044-bafa-84c64e4a03c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85e5163c-299a-4bdf-a20e-b27a49ca67b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0bbc08-8327-4cd5-a010-6e21a986df0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>783e0d89-0a11-499f-be63-17d76c8f1742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b012d0-4bef-4fdf-a0a6-e6408d881c30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6d6fae9f-ed51-40fe-816c-b79ee1497e40</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0c67f9-8272-4565-baee-df120321a811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4723b919-9dbc-4a33-bdca-c55c9bff6eb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>046e729f-c14f-4b1b-a729-fb4d9dc1f516</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe20d892-242f-47af-bc8d-a6aca51e093e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0fcf679-256f-4dec-8bc8-996dc79db3f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd48c16-4b00-422c-99e4-560d4e7126c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9f1c854a-33c4-499d-b6c0-4a4e6598e785</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90beadf8-695c-4378-9be5-9084ebea211f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c463fe-889d-49f1-b538-350101e555b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71794a57-fcda-462b-9fdb-bf3d2055f470</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d943bff4-4cd6-4bb7-b1a1-54618e54ab28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fdaa4b2-3358-45e1-bc3b-7d1d3f8e87e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78eaac24-1cee-4a75-8fb3-fcfaed5e9863</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e63bc58e-7c43-42ff-a123-b6880bb5f6b4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6dcb64f-8671-478d-a44e-9c98d8754681</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b350812e-7412-4dc2-b6ec-ecf97ebe2647</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>820135ba-5443-422f-95d6-167a5d55a6a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107b46de-3d05-42eb-a98d-8fc0d5f87657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c62c9c2-8997-4d0b-a975-1c10abc0c634</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67aba77a-cc75-4cbd-800f-f971076b1f6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ebeed0fc-f519-40d3-829a-ae9b85847bb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>813746f3-6069-4703-a727-db879657a629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac28cbef-cea9-45b3-a9e7-03dd0d823209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040af2e0-da32-4961-847d-d6fc906dd751</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73bc7752-ee8a-4819-8069-77d525aaeb45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df56715-8863-473a-a220-075411fb5224</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc83768-1feb-4846-8b70-847bbd3c2210</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cf1ce629-5e68-4436-b47c-dfd71aa99b9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec47646e-edbf-4474-823e-c2231ef8b71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38bdb975-1951-4ec6-b6b7-72ab64eda37a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0725c607-5084-44ed-9a22-249243ecef1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c822c1f8-7691-486c-a249-ce4a29443334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff8dbb-9ead-425e-8ff5-6518783c4bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837b926a-4819-427f-bac7-5638fef6ab44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6389fe19-584f-40ba-910c-3e8a7f5bce39</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c53a5a5-860d-420c-8e37-d74e61a0395a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e19c5e0a-56a5-4d17-8f67-9a7beef791f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef0ebcf-8cb5-4e6e-bc84-0e6988308365</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0733defd-5684-4707-b628-6be5a70d8481</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4affb3a-27c6-49ca-a450-7b1f89cc4feb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636febf9-f94a-4b18-b529-fa3a30471a58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>342abb49-f93b-4a5e-b624-145ba0a0796e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-20</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>31048721-c3ee-4c6c-be43-05387198bd2c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-21</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5e7eafb9-bda8-41ce-9b1c-d0e598c72511</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-22</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec47646e-edbf-4474-823e-c2231ef8b71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38bdb975-1951-4ec6-b6b7-72ab64eda37a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0725c607-5084-44ed-9a22-249243ecef1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c822c1f8-7691-486c-a249-ce4a29443334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff8dbb-9ead-425e-8ff5-6518783c4bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837b926a-4819-427f-bac7-5638fef6ab44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4af98210-59c8-4d8c-9b01-153fd40a2b5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-23</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d9f6d6d-15aa-4375-878e-48866812df4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b408e12-e729-4ca6-b544-ab564b6cf2f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0191d2aa-acc3-4efc-9dc7-6efb2b1a5214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b20afa52-5d0c-49df-a4b7-055f59359ad7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e4cc964-6830-491f-930c-256fab1542e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dbf3a021-859a-435d-8b3f-75484e84ce4f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06cdedd6-cd7a-4eb9-b118-775ae8457e8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-24</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1328cf42-d7f7-48bf-ae0b-2a64fd51781e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc5a9ce9-ea7a-491c-ac4e-141402ee5e82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f2a72bb-f1f9-4c13-be96-a65519614054</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01ad0965-e951-4d60-8683-1e42770b08b6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6e4f8ab-ce7f-4e96-a450-2e970859fcad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e0afa9a-84e1-484f-9d51-47132833926c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed3ded39-3c63-406a-ba07-8d88e2bf58bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-25</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23af1210-323f-4d44-91a5-e0d14d9a337a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38103c26-7395-4add-b61d-fd8a8f957a88</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>209c9df4-2457-4b0b-a9f5-786c9974aab4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>245ecd3b-0a99-4ec7-a867-e8c0995c4a60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fcb31ac-5869-4256-994d-bdeee1d469ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65a7dfdd-d494-42ac-8129-a59ab5cb33f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49874994-f8fc-43ed-b70e-9dceb1e198e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-26</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee5f2a72-d0a8-4e17-93ce-86d2687daff8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66f8f6aa-42d2-4849-bd79-3103b0cdb029</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17139584-04b9-4a4a-96f8-d3c209257c3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27b8d3af-583e-417e-adee-67a274c4bf33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837a5713-6c54-46bf-8daf-a350cde69823</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c993fc-6fc7-4cd8-8311-57d4af050031</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b6b064a6-2908-4ee1-bc7d-35b238fef90b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-27</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e97b95e-af08-4aa5-9942-2f7748b59172</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ace19e4-f22d-40e2-b3f9-9ef598d4e92d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5cc0dbd6-8031-4639-829f-05fccda86d79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b043b28d-14c4-4e0d-9e33-da3b365b30df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a1ca34b-5657-4a14-8bd9-e05bfbf2f074</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89a1eed8-d7d4-408e-a0ec-490512e14ddf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d33d354-2893-4cfa-bf06-5d671ec77331</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc3a1547-5190-4bc9-b325-01940b66cb52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56d19144-ecf2-49d6-98b0-183c10a87307</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>92642347-f94e-40dc-a59b-b5a7493ec2db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>864fc347-d5ab-4b03-95d3-836fdd6dc442</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f8206b-404b-4d1d-8eb2-d5d41f0bd1c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>994db4ac-ce64-421a-8a41-b1d0f0648adc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5789367e-5451-432c-b327-7c348d8b3d1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6215cee-f11d-4699-9a06-7f78bfabc160</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e9e738c-900b-4ef8-8076-523ce184545e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>541a4a7d-1712-434e-a714-80e9b48a7182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d526a7b-004f-489f-84b4-db91b7e53983</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3697967-e03e-41e9-918f-3f0a0865c900</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b24028e7-5d37-45c3-a0ac-23ae6ea79844</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cf1abd4-b412-446a-a447-e0e10554bb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a5e7a06-5e89-4034-a32e-dc8cbf0cd7d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42c5249a-1158-4a05-a101-4412e5433af2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f12a399e-a5ed-4238-9c5d-0d6e7784f6d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e428a761-3159-42ca-94fe-72ce8fc31488</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>610ef54b-aa79-4893-900a-e7dc836eccf6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d51d9e35-b6d6-47f7-b9d7-b94aecc55fdf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8cd4989b-cad6-49fb-8ea3-f8d47f21af48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56914696-c524-40a6-929a-a3df43d8d21f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf22793c-78d6-4eac-89cf-28cd7ed2cb49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9c6815f-ee5c-400f-986e-b00a073efde0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9eaba1b3-13a5-4e8b-b5d4-17a1fef6a17e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eacce546-54f5-457c-b047-8994d1bdf4ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9890e3b8-3e13-4c91-a531-4afca6b27ac9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e004fe40-defd-4ad4-b2dd-fc83a1926e94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>110be7f4-ff21-4310-a746-13da3b8444d4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
