<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-DB</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2f1e4992-da9c-433d-8857-8e4af214ba69</testSuiteGuid>
   <testCaseLink>
      <guid>d4b218bd-dfff-4cce-bc07-e8786126684a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73ff716a-5e06-4666-958e-cd331e044b31</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>885ea78e-3155-42a2-bf56-ead734d3712d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fba15357-a253-4880-b84d-4b35fe9d3b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a788f632-c232-4df7-a416-4be65315ed55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a6177094-fb40-46f3-880b-b284c4207582</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1fd9d963-0464-4be2-b783-2d30ac184370</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e07b034-455b-4ba2-b52a-856cfcef506d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5b4368a0-446c-4f6b-a8db-5ecc926b51a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04f417bd-d143-44db-b97d-fca5635962cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33d794f2-b596-4ef9-89d1-d49a88486fa2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f7557cb-a824-4352-b8a1-f4e586ed7129</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>024b9f72-af07-460d-9f7d-fa47a59efa95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>959540d4-bc10-4263-a618-5024d540cdd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c7feabe-ba79-4751-b3e2-bc10be8df31b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ad93912-eb4a-42c9-a127-dd1c2fdeaaa6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>260da65e-fcda-4f94-9b19-4809914d1637</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>734e9c5f-3844-476f-9aeb-7596441d83cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6793472a-ce86-4aeb-b505-25d4b44f0205</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1652a47e-e596-424d-a17f-5a142e8c6060</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ef1135-59c2-4bd4-be01-67def8b012b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2ac9844-0282-4be6-aabc-e04174c65479</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bad55f47-3372-4b2f-be11-598dd78b3a67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2cf98112-f63b-45b4-a026-7d33d2156496</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea644a46-c1a6-4185-8858-fd6b81fc425a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Data Bank/TC-DB-01-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f997cfe-b52c-4ee6-92c0-e935bacec801</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7a86d06-b711-4c6b-a009-22156160f98d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2edde69-fe52-41cd-831d-a04e2798bb2f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
