<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-EDT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ec2e7d61-66c4-4134-bfcd-3322b5cdc130</testSuiteGuid>
   <testCaseLink>
      <guid>0f541749-8fec-4595-ac7e-984a422dd066</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db13bb1a-522b-4885-96e3-074d53dd6fd3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec8b0d1-3bb0-4f3d-8b12-c95e6e688858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04246dc2-8bfe-479a-b6ac-0317ded7dd4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec8b0d1-3bb0-4f3d-8b12-c95e6e688858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c4be92e-ce94-47ea-9ec8-00ef2b76b588</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99bcf70-eb0e-47d7-bd71-564cfc41f208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e167e47-1bbe-42e1-92c0-f9c347ddadc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9e5a2f-91ba-41e3-bb74-4a8758025a6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3260a518-8107-4293-ab03-560dfbca9ccb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99bcf70-eb0e-47d7-bd71-564cfc41f208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e167e47-1bbe-42e1-92c0-f9c347ddadc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9e5a2f-91ba-41e3-bb74-4a8758025a6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1925e94-96c4-4945-b6d4-1e3c00b4f9c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6b1d6751-1c23-417b-93ae-a72684faaac8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>40cb1f1d-dfcd-46f8-94b9-95400ed9ef12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d44e49-29c8-40b9-a9b5-8d257a741cc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60f4e5c1-adcf-41d2-b403-56d0c3f773ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d44e49-29c8-40b9-a9b5-8d257a741cc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>530b0d41-14a8-499a-9803-dd63eab56e47</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ce0ffb7-c0ca-4f83-8aaf-76bd4cb035dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ee94e351-62cf-441b-acc3-cb05670435b0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c47d21e8-a9ea-4bc3-ad72-4ebf14ef2c47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>28c03841-da45-4791-ac41-728af233317d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520dd34f-a50b-4c38-80f8-a58601f52482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0a331a5-6aef-415f-ab25-0643d63d2bc1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6f70fedc-c1c7-4eb6-8bac-fc336c9abafb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a4849440-b3ef-40fe-840b-1724561ac3d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf1614fe-be17-4134-b3ca-cd6401670cdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f8af13a-f2d4-4b15-87bd-a00d38932144</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520dd34f-a50b-4c38-80f8-a58601f52482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f74f9bde-ece4-4f09-b779-44d8a32372f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5b08a6-b315-4915-864c-f4d434495980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57a49a35-e7c8-458f-ad8f-70e42185c7a6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5b08a6-b315-4915-864c-f4d434495980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87d3d6e6-990a-47cb-9a46-1b06472ee004</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5b08a6-b315-4915-864c-f4d434495980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ae027b2-95c9-490e-9b43-465dde143519</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-20</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bb5922ba-3131-4d73-8cf4-a19d329edd84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-21</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>0fd5ac9f-6ed4-4477-b746-82089bfda641</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-22</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da5473c-e479-4827-bf9f-ff8f1ccc1f6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e5cfd82-15bf-4ce9-9b49-eaeba39ef7be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ce48d4-64f9-441e-9cc3-3c7993dbde46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3875eb6d-38a3-4107-967f-0805b9bd72ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-23</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af713a82-c164-499d-9ec7-4b4f687d5e44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e9be2f0-50ec-42b9-8625-b1da5b82bf4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-24</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e5538286-1f01-4a60-a145-a7197ae0a583</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7f957b5-25eb-43a8-8bfb-838983c6be67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-25</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06026697-d2bc-43ee-9941-dbb084184408</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d734cb0-0a29-4060-87ee-a4bd277d1b59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-26</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb4c5f11-6473-4851-8c21-2c56a3b51d2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ad54d563-95f6-4f9e-a66e-a7e99b4c7acf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-27</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eeb4503e-30b9-4e74-aec2-706fe48241c2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
