<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_doa</name>
   <tag></tag>
   <elementGuidId>2af039af-3427-41e3-abee-8f3339044a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='doa_terbaik']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;doa_terbaik&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1383e517-48be-449a-9041-b6b7080d18cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-auth</value>
      <webElementGuid>a1a181b1-5e28-4b7c-83ea-6e99f89a6b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>doa_terbaik</value>
      <webElementGuid>50e7b22a-00f8-411d-bb0c-babfbd0859ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/div[@class=&quot;ps-order-tracking&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ps-section__content&quot;]/form[@class=&quot;ps-form--order-tracking&quot;]/div[@class=&quot;form-group&quot;]/textarea[@class=&quot;form-control form-auth&quot;]</value>
      <webElementGuid>44c45ac5-4e0f-414d-8ea9-461304c41504</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='doa_terbaik']</value>
      <webElementGuid>4a2558e1-b65d-4f6f-8aeb-a8cddc9bed63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f8f299e8-3ffc-4c31-b74b-6e4a16f52502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'doa_terbaik']</value>
      <webElementGuid>0bb347c1-149e-478d-b7ac-8959eb3780c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
