<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_kredit_btn btn-default btn-xs</name>
   <tag></tag>
   <elementGuidId>702e183d-0cb1-4886-91ae-3fb9fcef51b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;example1&quot;]/tbody/tr[1]/td[8]/center/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.btn-xs</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d451f9a5-45cb-466c-95d7-790aff3ab960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-xs</value>
      <webElementGuid>520c6c2d-dc1f-4fa2-ae5e-d177ed6e39c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sukses Data</value>
      <webElementGuid>5ad1af02-cde6-4730-bd16-130f596d883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/proses_withdraw/287/Pending</value>
      <webElementGuid>52b3175f-afb6-4524-bf19-91a34ddd7ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Yakin ingin mengubah status jadi Pending??')</value>
      <webElementGuid>50301d60-002b-405f-8d89-8fba9b2e9e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/center[1]/a[@class=&quot;btn btn-default btn-xs&quot;]</value>
      <webElementGuid>3476cec2-abcd-457c-a2c5-0ec9d19383cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;return confirm('Yakin ingin mengubah status jadi Pending??')&quot;]</value>
      <webElementGuid>c3400494-020b-4b70-9243-a48cde9957ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[8]/center/a[2]</value>
      <webElementGuid>20ad1550-4c77-4832-a049-9d9679a2b608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kredit'])[1]/following::a[2]</value>
      <webElementGuid>646ab6ff-f12c-4dd5-a1e0-1145d091bbb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sukses'])[1]/following::a[2]</value>
      <webElementGuid>f6393bc8-fe9a-49a1-9709-5b7608d62f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='irfan.afandi'])[1]/preceding::a[2]</value>
      <webElementGuid>60c81bd2-1684-41a7-b210-120ebd96af8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/proses_withdraw/287/Pending')]</value>
      <webElementGuid>03961deb-0d52-4df6-8378-bacca11d7d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>88d971a5-d96d-4fe2-bfe6-91b2d3736ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Sukses Data' and @href = 'https://10.9.2.63/ecommerce/administrator/proses_withdraw/287/Pending']</value>
      <webElementGuid>3e940eac-aa19-40bb-b927-c20911dfeaa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
