<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-DFTR-FINAL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2de3fdcf-b4a5-412f-9051-de4697f62960</testSuiteGuid>
   <testCaseLink>
      <guid>d75833d2-430d-4852-a3f7-6ce05878d8c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec47646e-edbf-4474-823e-c2231ef8b71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38bdb975-1951-4ec6-b6b7-72ab64eda37a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0725c607-5084-44ed-9a22-249243ecef1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c822c1f8-7691-486c-a249-ce4a29443334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff8dbb-9ead-425e-8ff5-6518783c4bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837b926a-4819-427f-bac7-5638fef6ab44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64968a87-a5b3-4e94-a952-24cf43333b22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9feaba6d-0f0b-482b-998c-3308b72fafdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f9430122-c8d4-4f5f-af59-4171bcd680dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b28a3dfc-adc4-41f0-92da-cd622d4ec656</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f8ea3be-3f14-4b69-b54d-83d792205d48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f511144-ed87-454f-bc7f-3332efacab38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>297b42b8-0a27-4b5d-9474-9cc21da53a75</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6691710b-d2e1-46bc-954e-358cbf50ab4b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a27bf70b-ec8d-4f18-9fdb-b09bd02c0e6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f301dff-542a-47b3-89e0-0272e296af06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b43a2a78-8d03-4968-9b6a-aa2915b97a60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20644f0f-443a-4072-bbc3-591f3ea8be9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>567db3cc-6f7e-4db1-a485-e74bcace8af3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0154a6da-285c-4dce-9406-cb45c591c55a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3fc2ecf9-6cc2-48c9-9e53-7b116ba66dba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c61358b7-a281-4c8d-8e27-5ddf8ef3c5cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb1e5709-85a2-4561-be4c-65078e68ac93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>875b93e7-8ff6-4824-bfa3-d36f83ed25f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95d4468d-f186-4f38-9dcb-28954af7bf89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1efa0bc6-f1c5-445e-acf1-06786fbc9b0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bbc7bb2d-633a-4c87-a2a0-a9d0084ef7af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10c8d0dc-70f2-4a9f-b38c-12843b09376b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d7cedb7-efc2-43be-bd7d-f8f34dcdf410</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>158f62d6-4f68-412d-a7c7-37f5c59d9aed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87415197-721b-4e31-937d-285f642418a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f066e1a-082f-4630-9bc6-6b87444ff28c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ea4b270-0717-4b93-9372-7c6633ee6596</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>611f0723-337e-43f1-a90f-5a3d13f76038</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bd0218a-3391-403f-a104-647e7d741d5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a11d165-0bef-4478-977c-c133fd858bd1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>'amor@b.com'</defaultValue>
         <description></description>
         <id>aa522ba4-306a-4951-9c97-3b75e6497ade</id>
         <masked>false</masked>
         <name>email</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-07</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>922332f2-2a41-4278-b1fa-c82df4bc04df</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData TS-DFTR-01</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48913f99-19ac-44b9-806c-dda871de4732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>922332f2-2a41-4278-b1fa-c82df4bc04df</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>email </value>
         <variableId>aa522ba4-306a-4951-9c97-3b75e6497ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96d9b1e8-d32e-47f9-9591-f44c4f348d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>769bcc24-e938-47ce-b330-c8e73a49caae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55a07483-b00a-4749-ae07-20db07c850e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>308d460e-5eac-406f-95fe-80474a0186f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed01d2a0-3a83-4f3c-a3c9-2429cf2d7c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abc72f22-ad44-4e1e-864b-1d812e0bf4c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df6781cd-5353-4efc-8d74-7467271cf85a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e0d3601-d6d6-4967-8c50-68a1e5b0bb32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>361749d0-9ad0-40af-9480-1cd00d880e27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a253f67-ad23-468a-966c-e7dcf8de56ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269004cd-9d06-4d15-962a-f99b481aeed4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>634de4a4-d587-4418-8dd4-b7feb4268196</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81d97f0c-3562-4fca-bee2-e36472901f67</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09aa359b-1453-47ff-9124-0c3faab83738</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56066f08-1d58-44a6-be84-6d0035b3f276</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7158473-d2bb-4e97-9c2e-20c1af756dab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b81fb07d-52e0-449a-b42f-6584ac6314e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aa703c1-a467-4675-b8e0-f87ebe69f8c1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42ffcf7f-8521-4300-85a5-0c67afb905e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f6b1a17-0b30-44f1-9ec9-b021bf9f03fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2f17ada-6815-4960-8515-c253cda45f7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eeec88e-76c6-425f-832c-4d553652a87d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b4ba69f-983e-4b9b-ae8a-c3da55c0ad56</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5196bf7c-a834-4e13-b0b0-5c41599aaa75</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>845cfb1a-9fa4-4a18-8a16-aaadefe66257</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>356f3049-2bca-4e78-86b3-49b1e4d95f3d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf6192ac-d66b-469f-b7fd-3f1943339414</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>279a5315-df2d-4b1b-853b-bb52cd044595</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea7a70bf-c7fb-4391-b567-cc9c83ff72da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de18cab2-c6b2-446a-8009-dc59f85b0203</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>39299d03-c9d6-42da-afa4-6768e6894a54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82c0d3e6-05de-4f8b-842f-6d19fa0168a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05bab105-8998-4ba8-a025-edcc446ca98f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d42c980-e053-40da-9401-2971bc8ab6bf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4856d8f2-1e2f-477a-a990-31b2f14d06eb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa1c5cd6-7089-4863-bd92-ce8912a42704</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>198bdf3c-5838-4044-bafa-84c64e4a03c3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85e5163c-299a-4bdf-a20e-b27a49ca67b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec0bbc08-8327-4cd5-a010-6e21a986df0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>783e0d89-0a11-499f-be63-17d76c8f1742</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74b012d0-4bef-4fdf-a0a6-e6408d881c30</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e78736e7-23b6-49a5-8011-5803ab318244</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a0c67f9-8272-4565-baee-df120321a811</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4723b919-9dbc-4a33-bdca-c55c9bff6eb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>046e729f-c14f-4b1b-a729-fb4d9dc1f516</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe20d892-242f-47af-bc8d-a6aca51e093e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0fcf679-256f-4dec-8bc8-996dc79db3f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd48c16-4b00-422c-99e4-560d4e7126c2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b4ae196-e798-4ca8-815e-bc285b41e881</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90beadf8-695c-4378-9be5-9084ebea211f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18c463fe-889d-49f1-b538-350101e555b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71794a57-fcda-462b-9fdb-bf3d2055f470</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d943bff4-4cd6-4bb7-b1a1-54618e54ab28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fdaa4b2-3358-45e1-bc3b-7d1d3f8e87e7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78eaac24-1cee-4a75-8fb3-fcfaed5e9863</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77e2181a-71d5-411d-853c-6a55ea12a5c6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6dcb64f-8671-478d-a44e-9c98d8754681</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b350812e-7412-4dc2-b6ec-ecf97ebe2647</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>820135ba-5443-422f-95d6-167a5d55a6a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107b46de-3d05-42eb-a98d-8fc0d5f87657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c62c9c2-8997-4d0b-a975-1c10abc0c634</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67aba77a-cc75-4cbd-800f-f971076b1f6b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e4039b5-3cbf-464c-8bc8-51c395bfc9e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>813746f3-6069-4703-a727-db879657a629</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac28cbef-cea9-45b3-a9e7-03dd0d823209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040af2e0-da32-4961-847d-d6fc906dd751</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73bc7752-ee8a-4819-8069-77d525aaeb45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8df56715-8863-473a-a220-075411fb5224</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc83768-1feb-4846-8b70-847bbd3c2210</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6c011e8e-cadc-4a32-a5c3-90b044ed74ee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec47646e-edbf-4474-823e-c2231ef8b71a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>38bdb975-1951-4ec6-b6b7-72ab64eda37a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0725c607-5084-44ed-9a22-249243ecef1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c822c1f8-7691-486c-a249-ce4a29443334</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aaff8dbb-9ead-425e-8ff5-6518783c4bf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>837b926a-4819-427f-bac7-5638fef6ab44</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77ef617a-ac20-42ee-9b6f-c0020ccabf17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c53a5a5-860d-420c-8e37-d74e61a0395a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e19c5e0a-56a5-4d17-8f67-9a7beef791f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ef0ebcf-8cb5-4e6e-bc84-0e6988308365</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0733defd-5684-4707-b628-6be5a70d8481</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4affb3a-27c6-49ca-a450-7b1f89cc4feb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>636febf9-f94a-4b18-b529-fa3a30471a58</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>982b9076-c742-4055-928e-35b54f0e83ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-20</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5ac1c723-57ed-4559-a4e2-ee6d806edbf9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-01-21</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>a6c10d53-d095-4f34-bb1a-ef55be60d38e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1e6e88cb-f965-4bfa-904a-47a14c83d799</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ts0201</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1e6e88cb-f965-4bfa-904a-47a14c83d799</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC-DFTR-02-01</value>
         <variableId>bc3a1547-5190-4bc9-b325-01940b66cb52</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56d19144-ecf2-49d6-98b0-183c10a87307</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>917ede43-02ac-429b-8198-3d8e9879db0f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>864fc347-d5ab-4b03-95d3-836fdd6dc442</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18f8206b-404b-4d1d-8eb2-d5d41f0bd1c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>09ce4e5d-9361-4a4c-9efe-a427f16c0b3b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5789367e-5451-432c-b327-7c348d8b3d1e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b6215cee-f11d-4699-9a06-7f78bfabc160</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3daf3e31-b9b9-46ca-9e7c-8d31c9d32b79</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>541a4a7d-1712-434e-a714-80e9b48a7182</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d526a7b-004f-489f-84b4-db91b7e53983</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bb97e057-4442-4b02-836a-fc63e95f5f2e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c2d0d06a-bd1c-4d8a-b942-4b86dedcaed2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cf1abd4-b412-446a-a447-e0e10554bb50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a5e7a06-5e89-4034-a32e-dc8cbf0cd7d9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94034a9f-4963-4aa0-add8-a63e6abe3bf3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>71e98f4e-8ed4-40ff-9654-573a1e8f447a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9fe33fbb-4c6d-40db-8150-e1cbffd17c71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>56dd1023-1559-4c1c-a9f8-0ddb16333f48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8085a8ed-38d6-4e52-bd34-ebd226851e54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6a0917f3-70b9-4514-9f17-8e789420cbb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pendaftaran/TC-DFTR-02-12</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f2b8ff4c-528a-42f0-ba05-b79a97fcf37a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData TS-DFTR-02</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f2b8ff4c-528a-42f0-ba05-b79a97fcf37a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC-DFTR-02-12 email</value>
         <variableId>56914696-c524-40a6-929a-a3df43d8d21f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f2b8ff4c-528a-42f0-ba05-b79a97fcf37a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TC-DFTR-02-12 no hp</value>
         <variableId>bf22793c-78d6-4eac-89cf-28cd7ed2cb49</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
