<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-EDT-FINAL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3818ff45-d717-428b-af65-7f7de36b8f36</testSuiteGuid>
   <testCaseLink>
      <guid>5b5e16b5-558a-4102-8825-9cc29ca3dca9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-01</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>53e7a397-7c46-4e02-8f70-bcba5df099da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec8b0d1-3bb0-4f3d-8b12-c95e6e688858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05107af3-8440-4dc0-bf65-b0f73bc13693</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ec8b0d1-3bb0-4f3d-8b12-c95e6e688858</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b2a9b27-1be1-4571-89f4-ae7227fc3773</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99bcf70-eb0e-47d7-bd71-564cfc41f208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e167e47-1bbe-42e1-92c0-f9c347ddadc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9e5a2f-91ba-41e3-bb74-4a8758025a6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d9d840e-b5da-4742-9726-cfea5c02c62c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-05</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99bcf70-eb0e-47d7-bd71-564cfc41f208</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e167e47-1bbe-42e1-92c0-f9c347ddadc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a9e5a2f-91ba-41e3-bb74-4a8758025a6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9968069d-8ecc-408d-a2ff-527bf560742b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f420885-3ca7-406b-b727-4ab9d91a9d94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c70759b-122b-4d07-81bc-44a4629f968d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d44e49-29c8-40b9-a9b5-8d257a741cc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d8da6a20-ba3a-43f1-9dc9-5ed3b1aeedad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-09</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3d44e49-29c8-40b9-a9b5-8d257a741cc9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e05a0777-9def-4c22-b27e-5485408dd3dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-10</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3d75e8cc-f725-4fbe-a7bd-7795537305ff</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EDT Kontak</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3d75e8cc-f725-4fbe-a7bd-7795537305ff</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>kontak toko</value>
         <variableId>4ce0ffb7-c0ca-4f83-8aaf-76bd4cb035dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>935046a1-6887-470f-9545-1ada055efa93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c47d21e8-a9ea-4bc3-ad72-4ebf14ef2c47</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f53f797-ef60-45e5-9524-de8b360a082e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520dd34f-a50b-4c38-80f8-a58601f52482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33df3674-7203-471a-bd77-d97049061b6f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>4f0cd27d-099b-47db-8896-15c61912318f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e4a5b74e-8b7c-447d-a63f-f2980c7c5d4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf1614fe-be17-4134-b3ca-cd6401670cdc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3db8c524-69c4-4703-8b25-c33ed1ae1444</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-16</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>520dd34f-a50b-4c38-80f8-a58601f52482</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5799dd9-e861-4595-9058-07eb6bb5814b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5b08a6-b315-4915-864c-f4d434495980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>42aa5339-071c-412f-80df-fba53930cffb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-18</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>636b90e8-0eeb-414b-b975-4cc997a47f16</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EDT Kontak</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>636b90e8-0eeb-414b-b975-4cc997a47f16</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>format gambar</value>
         <variableId>6c5b08a6-b315-4915-864c-f4d434495980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9eb0c8b7-74e5-4e27-825d-66b99447c4e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5b08a6-b315-4915-864c-f4d434495980</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3c479737-4da5-4247-a868-5135a69e8809</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-20</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>bbbcf572-c2c5-438e-99eb-68cd6e3233d1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-21</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>5becf096-6272-40c2-8f4e-22ec9ea69a29</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-22</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150c3cb7-fa3f-4338-b5fd-ac8f5320d1a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9da5473c-e479-4827-bf9f-ff8f1ccc1f6b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e5cfd82-15bf-4ce9-9b49-eaeba39ef7be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ce48d4-64f9-441e-9cc3-3c7993dbde46</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bf0b76cd-0020-419c-9bde-a3b53c6fa472</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Edit Toko/TC-EDT-01-23</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af713a82-c164-499d-9ec7-4b4f687d5e44</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
