<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS-JZK-FINAL</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4fb0341a-46ac-4f74-a4de-4a34c8de085a</testSuiteGuid>
   <testCaseLink>
      <guid>945fa399-1b73-4ecf-8218-e2c2b581edde</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-01</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>810b2744-9e40-434a-b7ee-568ee8d45ee7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData TS-JZK-01</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>810b2744-9e40-434a-b7ee-568ee8d45ee7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Jenis Zakat</value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fafaa3b5-ec6c-495a-bf59-e539021c5815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-02</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7ac18cad-d236-412e-aa04-f4ac7d48bbb3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-03</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8c0e6cfa-683b-42e4-b739-586a261122e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-04</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8525e92-f807-4e79-807a-addb932cfd26</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-05</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c69618ae-77f3-46ae-87ac-c2f4ac096345</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData TS-JZK-01</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c69618ae-77f3-46ae-87ac-c2f4ac096345</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>noHP</value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c69618ae-77f3-46ae-87ac-c2f4ac096345</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Digit</value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>70258942-571f-4260-ade1-f3edf262fa22</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-06</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5fc60726-1048-44b4-a594-e6fc35192004</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-07</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29d061ab-ac54-4fe3-91ef-fb990e790c9f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-08</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d29295b-f65a-482a-864b-ca752610db61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-09</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bd174266-c131-4580-bd71-3d8ff28042d8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestData TS-JZK-01</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bd174266-c131-4580-bd71-3d8ff28042d8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Metode</value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8dbe48e1-7c43-46df-a045-003cfeb61463</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4e7090e6-e03d-405d-ac79-7cf825863a73</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-11</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67ac0ebe-7d91-4750-8609-a8a6f8884d18</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ed79019-52e2-4c1f-a834-fdd982d72993</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20b95bd4-da80-4fa1-b4b6-4ab9c5291df7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>17224e30-601c-4167-96ce-c48d4de1ae99</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7c94aff-aaf3-4f7f-9b76-0ef0eecb33f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>128e7f27-706a-4dd5-8450-6b93e55dd7f5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db184431-ed78-4065-bb70-05c5d144fb23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>172ab934-95db-4456-8235-855e580ec2d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f134f251-7475-4340-b108-7779e0e53acc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e98c54-a3be-4f3c-afea-8264700db8dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>445495c1-d76e-4b09-b107-8e9506782779</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4e000c6-16df-4ee7-825e-ce60bba1cde2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Jemput Zakat Online/TC-JZK-01-15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
